version: "3"
services:
  neo4j:
    container_name: Neo4j-test
    image: neo4j:5.6.0
#    volumes:
#       - ./neo4j.conf:/conf/neo4j.conf
#       - ./data/server1:/var/lib/neo4j/data
#       - ./logs/server1:/var/lib/neo4j/logs
#       - ./conf/server1:/var/lib/neo4j/conf
#       - ./import/server1:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
#      - NEO4J_dbms_memory_heap_initial__size=512m
#      - NEO4J_dbms_memory_heap_max__size=2G
#      - NEO4J_apoc_uuid_enabled=true
#      - NEO4J_dbms_default__listen__address=0.0.0.0
#      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_initial_dbms_default__database=test
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]
#      - NEO4JLABS_PLUGINS='["apoc"]'
#      - NEO4J_apoc_import_file_use__neo4j__config=true
#      - NEO4J_dbms_shell_enabled=true
    networks: ["Neo4j-test"]
    restart: unless-stopped
networks: { Neo4j-test: {} }
volumes:
  Neo4j-test:
